Repository TerraMA2/satalertas-client, pull requests merged in 2020-12, with the labels that each got.

#250 Changed markers popup to get info dynamically
  src/app/components/app.module.ts
  src/app/components/map/map.component.css
  src/app/components/map/map.component.ts
  src/app/components/map/popup-link/popup-link.component.css
  src/app/components/map/popup-link/popup-link.component.html
  src/app/components/map/popup-link/popup-link.component.ts
  src/app/components/map/popup/popup.component.css
  src/app/components/map/popup/popup.component.html
  src/app/components/map/popup/popup.component.ts
  src/app/components/map/table/table.component.ts
  src/app/services/config.service.ts
  src/app/services/link-popup.service.ts
  src/app/services/map.service.ts
  src/app/services/popup.service.ts
Labels: enhancement

#251 Added report links to the marker popup
  src/app/components/final-report/final-report.component.html
  src/app/components/map/map.component.ts
  src/app/components/map/popup/popup.component.css
  src/app/components/map/popup/popup.component.html
  src/app/components/map/popup/popup.component.ts
  src/app/components/map/table/table.component.html
  src/app/components/report/report.component.html
  src/app/services/popup.service.ts
Labels: enhancement

#252 Removed link from createMarker method
  src/app/components/map/map.component.ts
  src/app/components/map/popup/popup.component.html
  src/app/components/map/popup/popup.component.ts
  src/app/components/map/table/table.component.ts
  src/app/services/popup.service.ts
Labels: enhancement

#253 Added filter to the popup route
  src/app/components/map/map.component.ts
  src/app/services/config.service.ts
  src/app/services/filter.service.ts
  src/app/services/popup.service.ts
Labels: enhancement

#254 Added type to the popup data
  src/app/components/map/map.component.ts
  src/app/components/map/popup/popup.component.html
  src/app/components/map/popup/popup.component.ts
  src/app/services/config.service.ts
  src/app/services/map.service.ts
  src/app/services/popup.service.ts
Labels: enhancement

#256 Added a verification to check if the table data is empty
  src/app/components/map/table/table.component.ts
Labels: bug

#258 Comment an if to allow filter to rerender the map
  src/app/components/map/map.component.ts
Labels: bug

#259 Refactoring and fixed interface bugs
  src/app/components/about/about.component.css
  src/app/components/about/about.component.html
  src/app/components/app.component.ts
  src/app/components/app.module.ts
  src/app/components/dashboard/graphics-area/graphics-area.component.html
  src/app/components/final-report/final-report.component.ts
  src/app/components/map/layer-tools/layer-tools.component.html
  src/app/components/map/map.component.ts
  src/app/components/map/popup/popup.component.css
  src/app/components/map/popup/popup.component.html
  src/app/components/map/table/table.component.html
  src/app/components/map/table/table.component.ts
  src/app/components/report/report.component.html
  src/app/components/sidebar/sidebar-menu/sidebar-item/sidebar-item.component.ts
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer-group.component.css
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer-group.component.html
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer-group.component.ts
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer/sidebar-layer.component.css
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer/sidebar-layer.component.html
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer/sidebar-layer.component.ts
  src/app/services/export.service.ts
  src/app/services/final-report.service.ts
  src/app/services/map.service.ts
  src/app/services/popup.service.ts
  src/app/services/report.service.ts
  src/assets/pdf.js.map
  src/styles.css
Labels: bug, enhancement

#261 Fixed table error when there's no data
  package-lock.json
  src/app/components/map/table/table.component.ts
Labels: bug

#263 Added variables checks on the final report
  src/app/components/final-report/final-report.component.ts
  src/app/services/map.service.ts
Labels: enhancement
