Repository TerraMA2/satalertas-client, pull requests merged in 2021-08, with the labels that each got.

#312 Added ndvi request separated from getSynthesis method
  src/app/components/app.component.ts
  src/app/components/filter/footer-filter-area/footer-filter-area.component.html
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
  src/app/components/map/map.component.ts
  src/app/components/synthesis/synthesis.component.ts
  src/app/models/conf-button.model.ts
  src/app/services/synthesis.service.ts
Labels: enhancement

#316 Refactoring
  package-lock.json
  src/app/components/modal.component/modal.component.ts
  src/app/components/settings/layers-advanced/layers-advanced-edition/layers-advanced-edition.component.html
  src/app/components/settings/layers-advanced/layers-advanced-edition/layers-advanced-edition.component.ts
  src/app/components/settings/layers-advanced/layers-advanced.component.html
  src/app/components/settings/layers-advanced/layers-advanced.component.ts
  src/app/components/settings/layers/layers.component.ts
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer/sidebar-layer.component.html
  src/app/components/sidebar/sidebar.component.ts
Labels: enhancement

#317 Removing unecessary codes
  src/app/components/settings/layers/layers.component.ts
Labels: enhancement

#318 Added state to the report table
  src/app/components/map/table/table.component.ts
  src/app/components/reports/report-list/report-list.component.html
  src/app/components/reports/report-list/report-list.component.ts
  src/app/components/reports/report/report.component.html
  src/app/components/sidebar/sidebar.component.ts
Labels: enhancement

#319 Added state to the table and filter
  src/app/components/app-routing.module.ts
  src/app/components/app.component.ts
  src/app/components/app.module.ts
  src/app/components/filter/alert-type-area/alert-type-area.component.ts
  src/app/components/filter/authorization-area/authorization-area.component.ts
  src/app/components/filter/class-area/class-area.component.html
  src/app/components/filter/class-area/class-area.component.ts
  src/app/components/filter/filter.component.html
  src/app/components/filter/filter.component.ts
  src/app/components/filter/specific-search-area/specific-search-area.component.ts
  src/app/components/filter/theme-area/theme-area.component.html
  src/app/components/filter/theme-area/theme-area.component.ts
  src/app/components/map/map.component.ts
  src/app/components/map/popup/popup.component.css
  src/app/components/map/popup/popup.component.html
  src/app/components/map/table/table.component.html
  src/app/components/reports/report-list/report-list.component.css
  src/app/components/reports/report-list/report-list.component.html
  src/app/components/reports/report-list/report-list.component.ts
  src/app/components/reports/report/report.component.ts
  src/app/components/settings/settings.component.ts
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer/sidebar-layer.component.html
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer/sidebar-layer.component.ts
  src/app/components/synthesis/synthesis.component.ts
  src/app/models/map-state.model.ts
  src/app/models/table-state.model.ts
  src/app/services/filter.service.ts
  src/app/services/map.service.ts
  src/app/services/navigation.service.ts
  src/app/services/report.service.ts
  src/assets/config/config.json
  src/assets/config/i18n/br.json
  src/assets/config/i18n/us.json
  src/assets/config/mpmt/i18n/br.json
  src/assets/config/mpmt/i18n/us.json
  src/assets/config/mpmt/mpmt-config.json
Labels: enhancement

#320 Refactoring map component and added guard authentication
  package-lock.json
  package.json
  src/app/components/app-routing.module.ts
  src/app/components/app.module.ts
  src/app/components/auth/auth.guard.ts
  src/app/components/filter/class-area/class-area.component.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/map/layer-tools/layer-tools.component.ts
  src/app/components/map/map.component.css
  src/app/components/map/map.component.html
  src/app/components/map/map.component.ts
  src/app/components/map/table/table.component.css
  src/app/components/map/table/table.component.html
  src/app/components/map/table/table.component.ts
  src/app/components/reports/report-list/report-list.component.html
  src/app/components/reports/report-list/report-list.component.ts
  src/app/components/reports/report/report.component.html
  src/app/components/reports/report/report.component.ts
  src/app/components/reports/reports.component.ts
  src/app/components/settings/settings.component.ts
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer/sidebar-layer.component.ts
  src/app/components/sidebar/sidebar.component.bkp
  src/app/components/sidebar/sidebar.component.ts
  src/app/models/sidebar-item.model.ts
  src/app/services/auth.service.ts
  src/app/services/dashboard.service.ts
  src/app/services/export.service.ts
  src/app/services/filter.service.ts
  src/app/services/group-view.service.ts
  src/app/services/group.service.ts
  src/app/services/info-columns.service.ts
  src/app/services/map.service.ts
  src/app/services/navigation.service.ts
  src/app/services/report.service.ts
  src/app/services/sidebar.service.ts
  src/app/services/synthesis.service.ts
  src/app/services/table.service.ts
  src/assets/config/config.json
  src/assets/config/mpmt/mpmt-config.json
  src/environments/environment.prod.ts.example
  src/environments/environment.ts.example
Labels: enhancement

#322 Refactoring on dashboard
  src/app/components/app.component.ts
  src/app/components/app.module.ts
  src/app/components/dashboard/card-area/card-area.component.html
  src/app/components/dashboard/card-area/card-area.component.ts
  src/app/components/dashboard/card-area/card-button/card-button.component.css
  src/app/components/dashboard/card-area/card-button/card-button.component.html
  src/app/components/dashboard/card-area/card-button/card-button.component.ts
  src/app/components/dashboard/charts-area/charts-area.component.css
  src/app/components/dashboard/charts-area/charts-area.component.html
  src/app/components/dashboard/charts-area/charts-area.component.ts
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/dashboard/graphics-area/graphics-area.component.html
  src/app/components/dashboard/graphics-area/graphics-area.component.ts
  src/app/components/map/map.component.ts
  src/app/components/reports/report/report.component.ts
  src/app/components/settings/layers-advanced/layers-advanced.component.ts
  src/app/components/sidebar/sidebar.component.ts
  src/app/models/alert.model.ts
  src/app/models/analysis-chart.model.ts
  src/app/models/analysis.model.ts
  src/app/models/param-alert.model.ts
  src/app/services/dashboard.service.ts
  src/app/services/filter.service.ts
  src/app/services/map.service.ts
Labels: enhancement

#323 Refactoring on the filter
  angular.json
  package-lock.json
  package.json
  src/app/components/about/about.component.ts
  src/app/components/app.component.ts
  src/app/components/app.module.ts
  src/app/components/filter/alert-type/alert-type.component.css
  src/app/components/filter/alert-type/alert-type.component.html
  src/app/components/filter/alert-type/alert-type.component.ts
  src/app/components/filter/authorization/authorization.component.css
  src/app/components/filter/authorization/authorization.component.html
  src/app/components/filter/authorization/authorization.component.ts
  src/app/components/filter/class/class.component.css
  src/app/components/filter/class/class.component.html
  src/app/components/filter/class/class.component.ts
  src/app/components/filter/filter.component.html
  src/app/components/filter/filter.component.ts
  src/app/components/filter/footer-filter-area/footer-filter-area.component.ts
  src/app/components/filter/footer-filter/footer-filter.component.css
  src/app/components/filter/footer-filter/footer-filter.component.html
  src/app/components/filter/footer-filter/footer-filter.component.ts
  src/app/components/filter/specific-search/specific-search.component.css
  src/app/components/filter/specific-search/specific-search.component.html
  src/app/components/filter/specific-search/specific-search.component.ts
  src/app/components/filter/theme/theme.component.css
  src/app/components/filter/theme/theme.component.html
  src/app/components/filter/theme/theme.component.ts
  src/app/components/header/header.component.ts
  src/app/components/map/map.component.ts
  src/app/components/map/table/table.component.ts
  src/app/components/reports/report-list/report-list.component.html
  src/app/components/reports/report-list/report-list.component.ts
  src/app/components/reports/report/report.component.ts
  src/app/components/synthesis/synthesis.component.ts
  src/app/models/filter-param.model.ts
  src/app/models/filter-specific-search.model.ts
  src/app/services/filter.service.ts
  src/app/services/map.service.ts
  src/app/services/synthesis.service.ts
  src/app/services/table.service.ts
  src/app/utils/util.ts
Labels: enhancement

#324 Updated primengs css theme
  angular.json
  src/app/components/dashboard/card-area/card-button/card-button.component.css
  src/app/components/dashboard/card-area/card-button/card-button.component.html
  src/app/components/dashboard/charts-area/charts-area.component.css
  src/app/components/filter/footer-filter/footer-filter.component.html
  src/app/components/header/header.component.css
  src/app/components/map/layer-tools/layer-tools.component.html
  src/app/components/map/layer-tools/layer-tools.component.ts
  src/app/components/map/map.component.css
  src/app/components/map/popup/popup.component.css
  src/app/components/map/popup/popup.component.html
  src/app/components/map/table/table.component.css
  src/app/components/map/table/table.component.html
  src/app/components/map/visible-layers/visible-layers.component.css
  src/app/components/map/visible-layers/visible-layers.component.ts
  src/app/components/reports/report-list/report-list.component.css
  src/app/components/reports/report-list/report-list.component.html
  src/app/components/reports/report/report.component.css
  src/app/components/reports/report/report.component.html
  src/app/components/settings/group-manager/group-list/group-list.component.html
  src/app/components/settings/settings-toolbar/settings-toolbar.component.html
  src/app/components/sidebar/sidebar-menu/sidebar-item/sidebar-item.component.css
  src/app/components/sidebar/sidebar-menu/sidebar-item/sidebar-item.component.html
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer-group.component.css
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer-group.component.html
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer/sidebar-layer.component.css
  src/app/components/sidebar/sidebar.component.css
  src/app/components/synthesis/synthesis.component.css
  src/app/components/synthesis/synthesis.component.html
  src/styles.css
  src/theme.css
Labels: enhancement

#325 B2.0.0 dev
  package-lock.json
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/settings/group-manager/group-list/group-list.component.ts
  src/app/components/settings/layers-advanced/layers-advanced-edition/layers-advanced-edition.component.html
  src/app/components/settings/layers-advanced/layers-advanced-edition/layers-advanced-edition.component.ts
  src/app/components/settings/layers-advanced/layers-advanced.component.html
  src/app/components/settings/layers-advanced/layers-advanced.component.ts
  src/app/components/settings/layers/layers.component.ts
  src/app/components/sidebar/sidebar.component.bkp
  src/app/components/sidebar/sidebar.component.ts
  src/app/models/group.model.ts
  src/app/models/layer-group.model.ts
  src/app/models/layer.model.ts
  src/app/services/group-view.service.ts
  src/assets/config/config.json
  src/assets/config/mpmt/mpmt-config.json
Labels: enhancement, Bugfix

#326 Added responsiveness to the header
  package-lock.json
  src/app/components/app.component.html
  src/app/components/app.module.ts
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/map/popup/popup.component.css
  src/styles.css
Labels: enhancement

#327 Added env.js
  .gitignore
  angular.json
  src/env.js
  src/environments/environment.prod.ts
  src/environments/environment.prod.ts.example
  src/environments/environment.ts
  src/index.html
Labels: enhancement

#328 B2.0.0 dev
  src/app/components/map/layer-tools/layer-tools.component.html
  src/app/components/map/layer-tools/layer-tools.component.ts
  src/app/components/map/map.component.ts
  src/app/components/map/table/table.component.ts
  src/app/components/map/visible-layers/visible-layers.component.ts
  src/app/components/reports/report-list/report-list.component.ts
  src/app/components/settings/layers-advanced/layers-advanced-edition/layers-advanced-edition.component.html
  src/app/components/settings/layers-advanced/layers-advanced.component.html
  src/app/components/settings/layers-advanced/layers-advanced.component.ts
  src/app/components/settings/layers/layers.component.ts
  src/app/components/sidebar/sidebar-menu/sidebar-item/sidebar-item.component.html
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer-group.component.html
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer/sidebar-layer.component.css
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer/sidebar-layer.component.html
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer/sidebar-layer.component.ts
  src/app/components/sidebar/sidebar.component.bkp
  src/app/components/sidebar/sidebar.component.ts
  src/app/models/layer-class.model.ts
  src/app/models/layer-group.model.ts
  src/app/models/layer.model.ts
  src/app/models/report-layer.model.ts
  src/app/models/sidebar-item.model.ts
  src/app/services/group-view.service.ts
  src/app/services/group.service.ts
  src/app/services/map.service.ts
  src/app/services/popup.service.ts
  src/app/services/sidebar.service.ts
Labels: enhancement, Bugfix

#329 Fix bug at setSidebarItems
  src/app/components/sidebar/sidebar.component.ts
Labels: Bugfix

#330 Removed terrama2Url variable and the login from terrama2
  src/app/components/auth/auth.component.ts
  src/app/services/auth.service.ts
  src/app/services/http.service.ts
  src/assets/config/config.json
  src/assets/config/mpmt/mpmt-config.json
  src/env.js
Labels: enhancement
