Repository TerraMA2/satalertas-client, pull requests merged in 2021-09, with the labels that each got.

#332 B2.0.0 dev
  src/app/components/app-routing.module.ts
  src/app/components/app.module.ts
  src/app/components/dashboard/card-area/card-area.component.ts
  src/app/components/map/map.component.ts
  src/app/components/map/table/table.component.html
  src/app/components/reports/report-list/report-list.component.ts
  src/app/components/settings/group-manager/group-list/group-list.component.html
  src/app/components/settings/group-manager/group-list/group-list.component.ts
  src/app/components/settings/info-columns/info-columns.component.css
  src/app/components/settings/info-columns/info-columns.component.html
  src/app/components/settings/info-columns/info-columns.component.ts
  src/app/components/settings/layers-advanced/layers-advanced-edition/layers-advanced-edition.component.html
  src/app/components/settings/layers-advanced/layers-advanced.component.html
  src/app/components/settings/layers-advanced/layers-advanced.component.ts
  src/app/components/settings/layers/layers.component.html
  src/app/components/settings/layers/layers.component.ts
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer/sidebar-layer.component.ts
  src/app/models/analysis-chart.model.ts
  src/app/models/analysis.model.ts
  src/app/models/layer-class.model.ts
  src/app/models/response.model.ts
  src/app/models/view.model.ts
  src/app/services/info-columns.service.ts
  src/app/services/map.service.ts
  src/app/services/popup.service.ts
  src/assets/config/config.json
  src/assets/config/mpmt/mpmt-config.json
Labels: enhancement, Bugfix

#333 Removed unused 'terramaUrl'
  src/app/services/http.service.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: bug

#334 Refactoring
  src/app/components/settings/info-columns/info-columns.component.html
  src/app/components/settings/info-columns/info-columns.component.ts
  src/app/services/info-columns.service.ts
Labels: Bugfix

#335 Error handling
  .editorconfig
  src/app/components/about/about.component.html
  src/app/components/about/about.component.ts
  src/app/components/app.component.html
  src/app/components/app.component.ts
  src/app/components/app.module.ts
  src/app/components/auth/auth.component.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/filter/theme/theme.component.ts
  src/app/components/map/layer-tools/layer-tools.component.ts
  src/app/components/map/map.component.ts
  src/app/components/map/table/table.component.ts
  src/app/components/reports/report-list/report-list.component.ts
  src/app/components/reports/report/report.component.ts
  src/app/components/sidebar/sidebar-menu/sidebar-item/sidebar-item.component.ts
  src/app/components/sidebar/sidebar.component.ts
  src/app/components/synthesis/synthesis.component.ts
  src/app/models/response.model.ts
  src/app/models/user.model.ts
  src/app/services/auth.service.ts
  src/app/services/dashboard.service.ts
  src/app/services/export.service.ts
  src/app/services/filter.service.ts
  src/app/services/group-view.service.ts
  src/app/services/group.service.ts
  src/app/services/http-interceptor.service.ts
  src/app/services/http.service.ts
  src/app/services/info-columns.service.ts
  src/app/services/map.service.ts
  src/app/services/report.service.ts
  src/app/services/sidebar.service.ts
  src/app/services/table.service.ts
Labels: enhancement

#336 Changes on message service and angular update
  package-lock.json
  package.json
  src/app/components/auth/auth.component.ts
  src/app/components/header/header.component.ts
  src/app/components/map/layer-tools/layer-tools.component.ts
  src/app/components/map/table/table.component.html
  src/app/components/modal.component/modal.component.ts
  src/app/components/reports/report-list/report-list.component.css
  src/app/components/reports/report-list/report-list.component.html
  src/app/components/reports/report-list/report-list.component.ts
  src/app/components/reports/report/report.component.html
  src/app/components/reports/report/report.component.ts
  src/app/components/settings/group-manager/group-list/group-list.component.html
  src/app/components/settings/group-manager/group-list/group-list.component.ts
  src/app/components/settings/info-columns/info-columns.component.html
  src/app/components/settings/info-columns/info-columns.component.ts
  src/app/components/settings/layers-advanced/layers-advanced-edition/layers-advanced-edition.component.html
  src/app/components/settings/layers-advanced/layers-advanced-edition/layers-advanced-edition.component.ts
  src/app/components/settings/layers-advanced/layers-advanced.component.html
  src/app/components/settings/layers-advanced/layers-advanced.component.ts
  src/app/components/settings/layers/layers.component.ts
  src/app/components/settings/settings-toolbar/settings-toolbar.component.ts
  src/app/components/settings/settings.component.ts
  src/app/services/export.service.ts
  src/app/services/http-interceptor.service.ts
Labels: enhancement

#337 Added pRipple to the buttons
  src/app/components/about/about.component.html
  src/app/components/app.component.ts
  src/app/components/app.module.ts
  src/app/components/auth/auth.component.html
  src/app/components/dashboard/card-area/card-button/card-button.component.html
  src/app/components/filter/footer-filter/footer-filter.component.html
  src/app/components/header/header.component.html
  src/app/components/map/layer-tools/layer-tools.component.html
  src/app/components/map/popup/popup.component.html
  src/app/components/map/table/table.component.html
  src/app/components/modal.component/modal.component.html
  src/app/components/reports/report-list/report-list.component.html
  src/app/components/reports/report/report.component.html
  src/app/components/settings/info-columns/info-columns.component.html
  src/app/components/settings/layers-advanced/layers-advanced-edition/layers-advanced-edition.component.html
  src/app/components/settings/layers-advanced/layers-advanced.component.html
  src/app/components/settings/layers/layers.component.html
  src/app/components/settings/settings-toolbar/settings-toolbar.component.html
  src/app/components/synthesis/synthesis.component.html
Labels: enhancement

#338 Changed translations json keys
  src/app/components/about/about.component.html
  src/app/components/app.component.ts
  src/app/components/auth/auth.component.html
  src/app/components/auth/auth.component.ts
  src/app/components/dashboard/card-area/card-area.component.ts
  src/app/components/dashboard/charts-area/charts-area.component.html
  src/app/components/filter/alert-type/alert-type.component.html
  src/app/components/filter/class/class.component.html
  src/app/components/filter/filter.component.html
  src/app/components/filter/footer-filter/footer-filter.component.html
  src/app/components/filter/specific-search/specific-search.component.html
  src/app/components/header/header.component.html
  src/app/components/map/layer-tools/layer-tools.component.html
  src/app/components/map/legend/legend.component.html
  src/app/components/map/popup/popup.component.html
  src/app/components/map/table/table.component.html
  src/app/components/map/visible-layers/visible-layers.component.html
  src/app/components/page-not-found/page-not-found.component.html
  src/app/components/reports/report-list/report-list.component.html
  src/app/components/reports/report-list/report-list.component.ts
  src/app/components/reports/report/report.component.html
  src/app/components/settings/group-manager/group-list/group-list.component.html
  src/app/components/synthesis/synthesis.component.html
  src/app/services/http-interceptor.service.ts
  src/app/services/report.service.ts
  src/assets/config/config.json
  src/assets/config/i18n/br.json
  src/assets/config/i18n/us.json
  src/assets/config/mpmt/i18n/br.json
  src/assets/config/mpmt/i18n/us.json
  src/assets/config/mpmt/mpmt-config.json
  src/styles.css
Labels: enhancement

#339 B2.0.0 dev
  src/app/components/app.module.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/map/popup/popup.component.html
  src/app/components/reports/report/report.component.html
  src/app/components/settings/group-manager/group-manager.component.html
  src/app/components/settings/info-columns/info-columns.component.css
  src/app/components/settings/info-columns/info-columns.component.html
  src/app/components/settings/info-columns/info-columns.component.ts
  src/app/components/settings/layers-advanced/layer-table/layer-table.component.css
  src/app/components/settings/layers-advanced/layer-table/layer-table.component.html
  src/app/components/settings/layers-advanced/layer-table/layer-table.component.ts
  src/app/components/settings/layers-advanced/layer-table/sub-layer-table/sub-layer-table.component.html
  src/app/components/settings/layers-advanced/layer-table/sub-layer-table/sub-layer-table.component.ts
  src/app/components/settings/layers-advanced/layers-advanced-edition/layers-advanced-edition.component.css
  src/app/components/settings/layers-advanced/layers-advanced-edition/layers-advanced-edition.component.html
  src/app/components/settings/layers-advanced/layers-advanced-edition/layers-advanced-edition.component.ts
  src/app/components/settings/layers-advanced/layers-advanced.component.html
  src/app/components/settings/layers-advanced/layers-advanced.component.ts
  src/app/components/settings/layers/layers.component.html
  src/app/components/settings/layers/layers.component.ts
  src/app/components/sidebar/sidebar.component.ts
  src/app/services/group-view.service.ts
  src/app/services/info-columns.service.ts
  src/app/services/settings.service.ts
Labels: enhancement

#340 Fixed responsiveness problems
  angular.json
  package-lock.json
  package.json
  src/app/components/about/about.component.html
  src/app/components/about/about.component.ts
  src/app/components/app.component.html
  src/app/components/app.component.ts
  src/app/components/app.module.ts
  src/app/components/auth/auth.component.html
  src/app/components/auth/auth.component.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/filter/filter.component.html
  src/app/components/filter/filter.component.ts
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/map/layer-tools/layer-tools.component.html
  src/app/components/map/layer-tools/layer-tools.component.ts
  src/app/components/map/legend/legend.component.html
  src/app/components/map/legend/legend.component.ts
  src/app/components/map/map.component.html
  src/app/components/map/map.component.ts
  src/app/components/map/search/search.component.css
  src/app/components/map/search/search.component.html
  src/app/components/map/search/search.component.ts
  src/app/components/map/table/table.component.html
  src/app/components/map/visible-layers/visible-layers.component.html
  src/app/components/map/visible-layers/visible-layers.component.ts
  src/app/components/reports/report-list/report-list.component.ts
  src/app/components/reports/report/report.component.html
  src/app/models/table-state.model.ts
  src/app/services/config.service.ts
  src/app/services/map.service.ts
  src/app/services/search.service.ts
  src/app/services/sidebar.service.ts
  src/app/utils/utm.ts
  src/assets/config/config.json
  src/assets/config/i18n/br.json
  src/assets/config/i18n/us.json
  src/assets/config/mpmt/i18n/br.json
  src/assets/config/mpmt/i18n/us.json
  src/assets/config/mpmt/mpmt-config.json
  src/assets/config/state-coords.json
  src/styles.css
Labels: enhancement

#341 Updated packages
  .editorconfig
  angular.json
  package-lock.json
  package.json
  src/app/components/about/about.component.html
  src/app/components/app.component.html
  src/app/components/app.module.ts
  src/app/components/auth/auth.component.html
  src/app/components/dashboard/card-area/card-area.component.html
  src/app/components/dashboard/charts-area/charts-area.component.html
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/filter/alert-type/alert-type.component.html
  src/app/components/filter/class/class.component.html
  src/app/components/filter/filter.component.html
  src/app/components/filter/footer-filter/footer-filter.component.html
  src/app/components/filter/specific-search/specific-search.component.html
  src/app/components/filter/theme/theme.component.html
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/map/layer-tools/layer-tools.component.html
  src/app/components/map/map.component.ts
  src/app/components/map/popup/popup.component.html
  src/app/components/map/popup/popup.component.ts
  src/app/components/map/search/search.component.html
  src/app/components/map/table/table.component.html
  src/app/components/modal.component/modal.component.html
  src/app/components/page-not-found/page-not-found.component.ts
  src/app/components/reports/report-list/report-list.component.html
  src/app/components/reports/report/report.component.html
  src/app/components/reports/reports.component.ts
  src/app/components/settings/group-manager/group-list/group-list.component.html
  src/app/components/settings/info-columns/info-columns.component.html
  src/app/components/settings/layers-advanced/layer-table/layer-table.component.html
  src/app/components/settings/layers-advanced/layer-table/sub-layer-table/sub-layer-table.component.html
  src/app/components/settings/layers-advanced/layers-advanced-edition/layers-advanced-edition.component.html
  src/app/components/settings/layers-advanced/layers-advanced.component.html
  src/app/components/settings/layers/layers.component.html
  src/app/components/settings/settings.component.html
  src/app/components/sidebar/sidebar-menu/sidebar-item/sidebar-item.component.html
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer-group.component.html
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer/sidebar-layer.component.html
  src/app/components/sidebar/sidebar-menu/sidebar-layer-group/sidebar-layer/sidebar-layer.component.ts
  src/app/components/synthesis/synthesis-chart/synthesis-chart-card/synthesis-chart-card.component.html
  src/app/components/synthesis/synthesis-chart/synthesis-chart.component.html
  src/app/components/synthesis/synthesis-legend/synthesis-legend.component.html
  src/app/components/synthesis/synthesis-ndvi/synthesis-ndvi.component.html
  src/app/components/synthesis/synthesis-property-data/synthesis-property-data.component.html
  src/app/components/synthesis/synthesis-section/synthesis-section.component.html
  src/app/components/synthesis/synthesis.component.ts
  src/app/services/auth.service.ts
  src/app/services/filter.service.ts
  src/app/services/map.service.ts
  src/app/services/popup.service.ts
  src/app/services/report.service.ts
  src/app/services/table.service.ts
  src/styles.css
Labels: enhancement

#342 Removed toPromise()
  src/app/components/app-routing.module.ts
  src/app/components/map/table/table.component.ts
  src/app/components/reports/report-list/report-list.component.ts
  src/app/components/reports/report/report.component.ts
  src/app/components/settings/layers-advanced/layer-table/sub-layer-table/sub-layer-table.component.ts
  src/app/services/dashboard.service.ts
  src/app/services/export.service.ts
  src/app/services/filter.service.ts
  src/app/services/group-view.service.ts
  src/app/services/group.service.ts
  src/app/services/http-interceptor.service.ts
  src/app/services/info-columns.service.ts
  src/app/services/map.service.ts
  src/app/services/report.service.ts
  src/app/services/sidebar.service.ts
  src/app/services/synthesis.service.ts
  src/app/services/table.service.ts
Labels: enhancement

#343 Fix bug at settings button
  package-lock.json
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/settings/layers-advanced/layer-table/layer-table.component.html
  src/app/components/settings/layers-advanced/layer-table/sub-layer-table/sub-layer-table.component.html
  src/app/components/settings/settings.component.ts
  src/app/services/navigation.service.ts
Labels: Bugfix

#344 Refactoring
  package-lock.json
  package.json
  src/app/components/auth/auth.component.ts
  src/app/components/header/header.component.ts
  src/app/components/reports/report/report.component.ts
  src/app/components/settings/layers-advanced/layers-advanced-edition/layers-advanced-edition.component.ts
  src/app/components/settings/layers-advanced/layers-advanced.component.ts
  src/app/components/settings/layers/layers.component.ts
  src/app/components/settings/settings.component.ts
  src/app/services/auth.service.ts
  src/app/services/navigation.service.ts
  src/app/services/settings.service.ts
Labels: enhancement

#345 Removed getBaseImageUrl() from some geoserver images
  src/app/components/reports/report/report.component.ts
  src/app/services/map.service.ts
Labels: enhancement

#346 Fix typos, removing not used codes
  src/app/components/reports/report/report.component.html
  src/app/components/reports/report/report.component.ts
Labels: enhancement, Bugfix

#348 Removed chart generation from synthesis
  src/app/components/reports/report/report.component.ts
  src/app/components/synthesis/synthesis.component.ts
  src/app/services/synthesis.service.ts
Labels: enhancement

#349 Fixed report reload
  src/app/components/reports/report/report.component.ts
  src/app/services/report.service.ts
Labels: bug

#350 Fixed report type change
  .editorconfig
  angular.json
  package-lock.json
  package.json
  src/app/components/reports/report/report.component.ts
  src/app/components/synthesis/synthesis.component.ts
  src/app/services/navigation.service.ts
Labels: bug

#351 Removed geoserver images from report
  src/app/components/reports/report/report.component.ts
  src/app/components/synthesis/synthesis-legend/synthesis-legend.component.html
  src/app/components/synthesis/synthesis-legend/synthesis-legend.component.ts
Labels: enhancement

#352 Moved some variables and methods to backend
  src/app/components/reports/report/report.component.ts
Labels: enhancement

#353 Removed pdfmake
  package-lock.json
  package.json
  src/app/components/reports/report/report.component.ts
  src/app/services/report.service.ts
Labels: enhancement

#354 Changed angular version on the package.json
  package-lock.json
  package.json
  src/assets/fonts/DejaVuSans-Bold.ttf
  src/assets/fonts/DejaVuSans-BoldOblique.ttf
  src/assets/fonts/DejaVuSans.ttf
  src/assets/fonts/DejaVuSansMono-Oblique.ttf
Labels: enhancement

#355 Removed format methods from the report
  src/app/components/reports/report/report.component.ts
  src/assets/icons/icon-128x128.png
  src/assets/icons/icon-144x144.png
  src/assets/icons/icon-152x152.png
  src/assets/icons/icon-192x192.png
  src/assets/icons/icon-384x384.png
  src/assets/icons/icon-512x512.png
  src/assets/icons/icon-72x72.png
  src/assets/icons/icon-96x96.png
  src/assets/img/ico/deter32x32.png
  src/assets/img/ico/prodes32x32.png
  src/assets/img/logos/deter.png
  src/assets/img/logos/dpi.png
  src/assets/img/logos/inpe.png
  src/assets/img/logos/prodes.png
  src/assets/img/logos/queimadas.png
  src/assets/img/logos/terrama2-large.png
  src/assets/img/logos/terrama2-powered-by.png
  src/assets/img/logos/terrama2-small.png
Labels: enhancement
